[Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 104, in form_handler
    mol_path = os.path.join(app.config["MOLECULE_UPLOADS"], smiles_no_special_chars[0:10])
  File "/home/et/personal_projects/rdkit-obabel-confgen/confab.py", line 24, in write_conformers
    print(conf_nr)
OSError: [Errno 5] Input/output error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 106, in form_handler
  File "/home/et/personal_projects/rdkit-obabel-confgen/confab.py", line 24, in write_conformers
    print(conf_nr)
OSError: [Errno 5] Input/output error
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 53, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 63, in block "form"
    <a class="nav-link" href="{{ url_for('rdkit') }}">RDKit</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 53, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 63, in block "form"
    <a class="nav-link" href="{{ url_for('rdkit') }}">RDKit</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 53, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 63, in block "form"
    <a class="nav-link" href="{{ url_for('rdkit') }}">RDKit</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'rdkit'. Did you mean 'index' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 118, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 118, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 118, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 54, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 60, in block "form"
    <a class="nav-link active" aria-current="page" href="{{ url_for('confab') }}">Confab</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 54, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 60, in block "form"
    <a class="nav-link active" aria-current="page" href="{{ url_for('confab') }}">Confab</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 54, in index
    return render_template("index.html")
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 56, in top-level template code
    {% block form %}
  File "/home/et/personal_projects/rdkit-obabel-confgen/templates/index.html", line 60, in block "form"
    <a class="nav-link active" aria-current="page" href="{{ url_for('confab') }}">Confab</a>
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'confab'. Did you mean 'form_handler' instead?
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
'function' object has no attribute 'generate_conformers'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 120, in form_handler
    mole = confab.generate_conformers(smiles, force_field)
AttributeError: 'function' object has no attribute 'generate_conformers'
name 'method' is not defined
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 117, in form_handler
    print(method)
NameError: name 'method' is not defined
name 'method' is not defined
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 95, in form_handler
    if method == "confab":
NameError: name 'method' is not defined
Could not build url for endpoint 'confab'. Did you mean 'confab_page' instead?
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 87, in serve_pdbs
    return redirect(url_for("confab"))
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'confab'. Did you mean 'confab_page' instead?
